FitLife/Areas/Admin/Controllers/EventController.cs
using FitLife.Core.Contracts;
using FitLife.Web.Areas.Admin.Models;
using FitLife.Web.Areas.Admin.Models.Event;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FitLife.Web.Areas.Admin.Controllers
{
    public class EventController : AdminBaseController
    {
        private readonly ITrainerService trainerService;
        private readonly IEventService eventService;

        public EventController(ITrainerService _trainerService,
            IEventService _eventService)
        {
            trainerService = _trainerService;
            eventService = _eventService;
        }

        public async Task<IActionResult> Mine()
        {
            var myEvents = new MyEventViewModel();
            myEvents.JoinedEvents = await eventService.AllEventsByParticipantAsync(User.Id());

            var trainerId = await trainerService.GetTrainerByIdAsync(User.Id());

            if (trainerId != null)
            {
                myEvents.AddedEvents = await eventService.AllEventsByTrainerAsync(trainerId);

            }

            return View(myEvents);
        }
    }
}

FitLife/Areas/Admin/Controllers/ParticipantController.cs
using FitLife.Core.Contracts;
using FitLife.Core.Services;
using FitLife.Web.ViewModels.Participant;
using Microsoft.AspNetCore.Mvc;

namespace FitLife.Web.Areas.Admin.Controllers
{
	public class ParticipantController : AdminBaseController
	{
		private readonly IParticipantService participantService;
        private readonly ITrainerService trainerService;

		public ParticipantController(IParticipantService _participantService, ITrainerService _trainerService)
        {
            participantService = _participantService;
            trainerService = _trainerService;
        }

        [HttpGet]
        public async Task<IActionResult> Hire([FromQuery] AllParticipantsQueryModel model)
        {

            var participants = await participantService.GetParticipantsAsync(model.SearchTerm);


            model.TotalParticipantsCount = participants.TotalParticipantsCount;
            model.Participants = participants.Participants;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Hire(string id)
        {
            if (await participantService.ExistsByIdAsync(id) == false)
            {
                return BadRequest();
            }

            if (await trainerService.ExistsByIdAsync(id))
            {
                return BadRequest();
            }

            var participant = await participantService.GetByIdAsync(id);

            if (participant != null)
            {
                await trainerService.HireParticipantAsync(participant);
            }

            return RedirectToAction(nameof(Hire));

        }
    }
}

FitLife/Areas/Admin/Controllers/TrainerController.cs
using FitLife.Core.Contracts;
using FitLife.Core.Services;
using FitLife.Data.Models;
using FitLife.Web.ViewModels.Event;
using FitLife.Web.ViewModels.Participant;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FitLife.Web.Areas.Admin.Controllers
{
	public class TrainerController : AdminBaseController
	{		
		private readonly IParticipantService participantService;
		private readonly ITrainerService trainerService;

        public TrainerController(IParticipantService _participantService, ITrainerService _trainerService)
        {
			participantService = _participantService;
			trainerService = _trainerService;
        }

		[HttpGet]
        public async Task<IActionResult> All()
        {
            var allTrainers = await trainerService.AllAsync();
            return View(allTrainers);
        }

        
	}
}

FitLife/Controllers/ProductController.cs
using FitLife.Controllers;
using FitLife.Core.Contracts;
using FitLife.Web.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static FitLife.GlobalConstants.AdminConstants;

namespace FitLife.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService productService;
        private readonly IParticipantService participantService;
        private readonly ITrainerService trainerService;

        public ProductController(IProductService _productService,
            IParticipantService _participantService,
            ITrainerService _trainerService)
        {
            productService = _productService;
            participantService = _participantService;
            trainerService = _trainerService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllProductsQueryModel model)
        {

            var products = await productService.AllAsync(model.SearchTerm, model.Sorting);


            model.TotalProductsCount = products.TotalProductsCount;
            model.Products = products.Products;

            return View(model);
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if (await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await productService.ProductDetailsByIdAsync(id);

            return View(model);
        }

        [Authorize(Roles = AdminRole)]
        [HttpGet]
        public IActionResult Add()
        {
            var model = new ProductFormModel();

            return View(model);
        }

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> Add(ProductFormModel model)
        {
            if (ModelState.IsValid == false)
            {
                return BadRequest();
            }

            string newProduct = await productService.CreateAsync(model);

            return RedirectToAction(nameof(All));
        }

        [Authorize(Roles = AdminRole)]
        [HttpGet]
        public async Task<IActionResult> Modify(string id)
        {

            if (await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }
            if (id == "")
            {
                return BadRequest();
            }
            var model = await productService.GetProductModifyModelByIdAsync(id);

            return View(model);
        }

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> Modify(ProductModifyModel model)
        {
            if (await productService.ExistsAsync(model.Id) == false)
            {
                return BadRequest();
            }

            if (User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            await productService.ModifyAsync(model.Id, model);

            return RedirectToAction("ProductOptions", "Home", new { area = AdminArea });
        }

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            await productService.DeleteAsync(id);

            return RedirectToAction("ProductOptions", "Home", new { area = AdminArea });
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(string id)
        {
            if(await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            await productService.AddToCartAsync(id, User.Id());

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Mine()
        {                   

             var products = await productService.AllProductsByParticipantAsync(User.Id());            

            return View(products);
        }
    }
}

FitLife/Areas/Admin/Views/Shared/_AdminPartial.cshtml
@inject SignInManager<Participant> SignInManager
@inject UserManager<Participant> UserManager
@inject ITrainerService trainerService
<link rel="stylesheet" href="~/css/layout-admin.css" />

@{
	string userName = string.Empty;

	if (SignInManager.IsSignedIn(User))
	{
		userName = User.FindFirstValue(UserFullNameClaim) ?? string.Empty;

	}
}
<ul class="navbar-nav">
	@if (SignInManager.IsSignedIn(User))
	{
		<li class="nav-item">
			<a class="nav-link text-dark" asp-area="" asp-controller="/" asp-action="">Public Interface</a>
		</li>

		<li class="dropdown">
			<button class="btn-settings dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
				Hello, @userName!
			</button>
			<ul class="dropdown-menu">
				<li><a class="dropdown-item" asp-area="Admin" asp-controller="TrainingProgram" asp-action="Mine">My Programs</a></li>
				<li><a class="dropdown-item" asp-area="Admin" asp-controller="Event" asp-action="Mine">My Events</a></li>
				<li><a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Mine">Cart</a></li>
			</ul>
		</li>
		

			
	}
	else
	{
		<li class="nav-item">
			<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
		</li>
	}
</ul>

FitLife/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - FitLife</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/FitLife.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/layout-admin.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3" >
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Dashboard">FitLife</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Admin" asp-controller="Participant" asp-action="Hire">Hire a Trainer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Options">Product's options</a>
						</li>	
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Admin" asp-controller="Trainer" asp-action="All">All Trainers</a>
						</li>

					</ul>
					<partial name="_AdminPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - FitLife - <span class="text-danger">Admin Area</span>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FitLife/Areas/Admin/Views/Shared/_ParticipantPartial.cshtml
@model ParticipantServiceModel

<div class="col-md-4">
    <div class="card mb-3">        
        <div class="card-body text-center">
            <h4>@(Model.FirstName + " " + Model.LastName)</h4>
            <h6>@Model.Email</b></h6>
            
            <form class="ml-2" asp-area="Admin" asp-controller="Participant"
                  asp-action="Hire" asp-route-id="@Model.Id" method="post">
                <input class="btn btn-primary" type="submit" value="Hire" />
            </form>

        </div>
    </div>
</div>

FitLife/Areas/Admin/Views/Shared/_ProductOptionsPartial.cshtml
@model ProductServiceModel
@inject ITrainerService trainerService
@inject IProductService eventService
<link rel="stylesheet" href="~/css/Products.css" />

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Product Image">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h6><b>@Model.Price lv</b></h6>
            <br />
            <a asp-area="" asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Details</a>
            <a asp-area=""  asp-controller="Product" asp-action="Modify" asp-route-id="@Model.Id"
               class="btn btn-warning">Modify</a>
               <br/>
            <form class="ml-2" asp-area="" asp-controller="Product"
                  asp-action="Delete" asp-route-id="@Model.Id" method="post">
                <input class="btn btn-danger" type="submit" value="Delete" />
            </form>
        </div>
    </div>
</div>

FitLife/Areas/Admin/Views/Shared/_TrainerPartial.cshtml
@model ParticipantServiceModel

<div class="col-md-4">
    <div class="card mb-3">        
        <div class="card-body text-center">
            <h4>@(Model.FirstName + " " + Model.LastName)</h4>
            <h6>@Model.Email</b></h6>
            
            <form class="ml-2" asp-area="Admin" asp-controller="Trainer"
                  asp-action="Hire" asp-route-id="@Model.Id" method="post">
                <input class="btn btn-primary" type="submit" value="Hire" />
            </form>

        </div>
    </div>
</div>