FitLife/Areas/Admin/Controllers/EventController.cs
using FitLife.Core.Contracts;
using FitLife.Web.Areas.Admin.Models;
using FitLife.Web.Areas.Admin.Models.Event;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FitLife.Web.Areas.Admin.Controllers
{
    public class EventController : AdminBaseController
    {
        private readonly ITrainerService trainerService;
        private readonly IEventService eventService;

        public EventController(ITrainerService _trainerService,
            IEventService _eventService)
        {
            trainerService = _trainerService;
            eventService = _eventService;
        }

        public async Task<IActionResult> Mine()
        {
            var myEvents = new MyEventViewModel();
            myEvents.JoinedEvents = await eventService.AllEventsByParticipantAsync(User.Id());

            var trainerId = await trainerService.GetTrainerByIdAsync(User.Id());

            if (trainerId != null)
            {
                myEvents.AddedEvents = await eventService.AllEventsByTrainerAsync(trainerId);

            }

            return View(myEvents);
        }
    }
}

FitLife/Areas/Admin/Controllers/TrainingProgramController.cs
using FitLife.Core.Contracts;
using FitLife.Web.Areas.Admin.Models;
using FitLife.Web.Areas.Admin.Models.TrainingProgram;
using FitLife.Web.ViewModels.TrainingProgram;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FitLife.Web.Areas.Admin.Controllers
{
	public class TrainingProgramController : AdminBaseController
	{
		private readonly ITrainerService trainerService;
		private readonly ITrainingProgramService trainingProgramService;

		public TrainingProgramController(ITrainerService _trainerService,
			ITrainingProgramService _trainingProgramService)
		{
			trainerService = _trainerService;
			trainingProgramService = _trainingProgramService;
		}

        public async Task<IActionResult> Mine()
        {
            var myTrainingPrograms = new MyTrainingProgramViewModel();
            myTrainingPrograms.SubscribedTrainingPrograms = await trainingProgramService.AllTrainingProgramsByParticipantAsync(User.Id());

            var trainerId = await trainerService.GetTrainerByIdAsync(User.Id());

            if (trainerId != null)
            {
                myTrainingPrograms.AddedTrainingPrograms = await trainingProgramService.AllTrainingProgramsByTrainerAsync(trainerId);

            }

            return View(myTrainingPrograms);
        }
    }
}

FitLife/Controllers/ProductController.cs
using FitLife.Controllers;
using FitLife.Core.Contracts;
using FitLife.Web.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static FitLife.GlobalConstants.AdminConstants;

namespace FitLife.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService productService;
        private readonly IParticipantService participantService;
        private readonly ITrainerService trainerService;

        public ProductController(IProductService _productService,
            IParticipantService _participantService,
            ITrainerService _trainerService)
        {
            productService = _productService;
            participantService = _participantService;
            trainerService = _trainerService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllProductsQueryModel model)
        {

            var products = await productService.AllAsync(model.SearchTerm, model.Sorting);


            model.TotalProductsCount = products.TotalProductsCount;
            model.Products = products.Products;

            return View(model);
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if (await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await productService.ProductDetailsByIdAsync(id);

            return View(model);
        }

        [Authorize(Roles = AdminRole)]
        [HttpGet]
        public IActionResult Add()
        {
            var model = new ProductFormModel();

            return View(model);
        }

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> Add(ProductFormModel model)
        {
            if (ModelState.IsValid == false)
            {
                return BadRequest();
            }

            string newProduct = await productService.CreateAsync(model);

            return RedirectToAction(nameof(All));
        }

        [Authorize(Roles = AdminRole)]
        [HttpGet]
        public async Task<IActionResult> Modify(string id)
        {

            if (await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }
            if (id == "")
            {
                return BadRequest();
            }
            var model = await productService.GetProductModifyModelByIdAsync(id);

            return View(model);
        }

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> Modify(ProductModifyModel model)
        {
            if (await productService.ExistsAsync(model.Id) == false)
            {
                return BadRequest();
            }

            if (User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            await productService.ModifyAsync(model.Id, model);

            return RedirectToAction("ProductOptions", "Home", new { area = AdminArea });
        }

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            await productService.DeleteAsync(id);

            return RedirectToAction("ProductOptions", "Home", new { area = AdminArea });
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(string id)
        {
            if(await productService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            await productService.AddToCartAsync(id, User.Id());

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Mine()
        {                   

             var products = await productService.AllProductsByParticipantAsync(User.Id());            

            return View(products);
        }
    }
}

FitLife/Views/Shared/_EventFormPartial.cshtml
@model EventFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" placeholder="Title...">
                <span asp-validation-for="Title" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" placeholder="Description...">
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <textarea asp-for="ImageUrl" rows="4" class="form-control" placeholder="Image Url"></textarea>
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control">
                <span asp-validation-for="Address" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City"></label>
                <input asp-for="City" class="form-control">
                <span asp-validation-for="City" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime"></label>
                <input asp-for="StartTime" class="form-control" placeholder="dd/MM/yyyy HH:mm">
                <span asp-validation-for="StartTime" class="small text-danger"></span>
            </div>           
            <div class="mb-3">
                <label asp-for="@Model.CategoryId" class="form-label-add-edit">Select Category</label>
                <select asp-for="@Model.CategoryId" class="form-control" aria-required="true">
                    <option disabled selected value="">Select Category...</option>
                    @foreach (var category in Model.EventCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

FitLife/Views/Shared/_EventPartial.cshtml
@model EventServiceModel
@inject ITrainerService trainerService
@inject IEventService eventService
<link rel="stylesheet" href="~/css/page-layout.css" />
<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="TrainingProgram Image" height="300">
        <div class="card-body text-center">
            <h4>@Model.Title</h4>
            <h6>Start Date: <b>@Model.StartTime.ToString("dd/MM/yyyy hh:mm")</b></h6>
            <h6>
                Address:
                <b>@Model.Address</b>
            </h6>
            <h6>
                City:
                <b>@Model.City</b>
            </h6>
            <h6>
                Trainer:
                <b>@Model.CreatorName</b>
            </h6>
            <h6>
                Category:
                <b>@Model.CategoryName</b>
            </h6>
            <br />
            <a asp-controller="Event" asp-action="Details" asp-route-id="@Model.Id"
               class="btn-details">Details</a>

            @if (this.User.Identity.IsAuthenticated)
            {
                @if (await eventService.HasTrainerWithIdAsync(Model.Id, User.Id()) || User.IsAdmin())
                {
                    <a asp-controller="Event" asp-action="Modify" asp-route-id="@Model.Id"
                       class="btn-modify">Modify</a>
                }
                if (await trainerService.ExistsByIdAsync(User.Id()) == false)
                {
                    @if (await eventService.HasParticipantWithIdAsync(@Model.Id, User.Id()))
                    {
                        <br />
                        <br />
                        <form class="ml-2" asp-controller="Event"
                              asp-action="Join" asp-route-id="@Model.Id" method="post">
                            <input class="btn-subscribed" type="submit" value="Joined" disabled />
                        </form>
                    }
                    else
                    {
                        <br />
                        <br />
                        <form class="ml-2" asp-controller="Event"
                              asp-action="Join" asp-route-id="@Model.Id" method="post">
                            <input class="btn-subscribe" type="submit" value="Join" />
                        </form>
                    }

                }
            }
            else
            {
                <a asp-area="Identity" asp-page="/Account/Register"
                   class="btn btn-primary">Join</a>


            }

        </div>
    </div>
</div>

FitLife/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - FitLife</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/FitLife.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/layout.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FitLife</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="TrainingProgram" asp-action="All">Training Programs</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="All">Events</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="All">Store</a>
						</li>


					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - FitLife - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/toastr/toastr.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)

	@if (TempData[UserMessageSuccess] != null)
	{
		<script defer>
			message.showSuccess('@TempData[UserMessageSuccess]');
		</script>	
	}
	@if (TempData[UserMessageError] != null)
	{
		<script defer>
			message.showError('@TempData[UserMessageError]');
		</script>
	}
</body>
</html>

FitLife/Views/Shared/_ProductCartPartial.cshtml
@model ProductServiceModel
<link rel="stylesheet" href="~/css/Products.css" />

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Product Image">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h6><b>@Model.Price lv</b></h6>
            <br />          
         </div>
    </div>
</div>

FitLife/Views/Shared/_ProductFormPartial.cshtml
@model ProductFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" placeholder="Description...">
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <textarea asp-for="ImageUrl" rows="4" class="form-control" placeholder="Image Url"></textarea>
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvailableStockCount"></label>
                <input asp-for="AvailableStockCount" class="form-control">
                <span asp-validation-for="AvailableStockCount" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count"></label>
                <input asp-for="Count" class="form-control" placeholder="dd/MM/yyyy HH:mm">
                <span asp-validation-for="Count" class="small text-danger"></span>
            </div>            

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

FitLife/Views/Shared/_ProductPartial.cshtml
@model ProductServiceModel
@inject ITrainerService trainerService
<link rel="stylesheet" href="~/css/Products.css" />

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="TrainingProgram Image">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h6><b>@Model.Price lv</b></h6>            
            <br />
            <a asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Details</a>

            @if(await trainerService.ExistsByIdAsync(User.Id()) == false || User.IsAdmin())
            {
                @if (this.User.Identity.IsAuthenticated)
                {
                    <form class="ml-2" asp-area="" asp-controller="Product"
                          asp-action="AddToCart" asp-route-id="@Model.Id" method="post">
                        <input class="btn btn-warning" type="submit" value="Add To Cart" />
                    </form>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Register"
                       class="btn btn-primary">Add to Cart</a>
                }
            }
            

        </div>
    </div>
</div>

FitLife/Views/Shared/_TrainingProgramFormPartial.cshtml
@model TrainingProgramFormModel
<link rel="stylesheet" href="~/css/add.css" />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" placeholder="Title...">
                <span asp-validation-for="Title" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" placeholder="Description...">
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <textarea asp-for="ImageUrl" rows="4" class="form-control" placeholder="Image Url"></textarea>
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate"></label>
                <input asp-for="StartDate" class="form-control" placeholder="dd/MM/yyyy HH:mm">
                <span asp-validation-for="StartDate" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DurationDays"></label>
                <input asp-for="DurationDays" class="form-control">
                <span asp-validation-for="DurationDays" class="small text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.CategoryId" class="form-label-add-edit">Select Category</label>
                <select asp-for="@Model.CategoryId" class="form-control" aria-required="true">
                    <option disabled selected value="">Select Category...</option>
                    @foreach (var category in Model.TrainingProgramCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn-add" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>

FitLife/Views/Shared/_TrainingProgramPartial.cshtml
@model TrainingProgramServiceModel
@inject ITrainerService trainerService
@inject ITrainingProgramService trainingProgramService
<link rel="stylesheet" href="~/css/page-layout.css">

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img" src="@Model.ImageUrl" alt="TrainingProgram Image">
        <div class="card-body text-center">
            <h4>@Model.Title</h4>
            <h6>Start Date: <b>@Model.StartDate.ToString("dd/MM/yyyy hh:mm")</b></h6>
            <h6>
                Duration
                <b>@Model.Duration days</b>
            </h6>
            <h6>
                Trainer:
                <b>@Model.CreatorName</b>
            </h6>
            <h6>
                Category:
                <b>@Model.CategoryName</b>
            </h6>
            <br />
            <a asp-controller="TrainingProgram" asp-action="Details" asp-route-id="@Model.Id"
                class="btn-details">Details</a>

            @if (this.User.Identity.IsAuthenticated)
            {
                @if (await trainingProgramService.HasTrainerWithIdAsync(Model.Id, User.Id()) || User.IsAdmin())
                {
                    <a asp-controller="TrainingProgram" asp-action="Modify" asp-route-id="@Model.Id" 
                       class="btn-modify">Modify</a>
                }

                if(await trainerService.ExistsByIdAsync(User.Id()) == false)
                {                    
                    @if(await trainingProgramService.HasParticipantWithIdAsync(@Model.Id, User.Id()))
                    {
                        <br />
                        <br />
                        <form class="ml-2" asp-controller="TrainingProgram"
                              asp-action="Subscribe" asp-route-id="@Model.Id" method="post">
                            <input class="btn-subscribed" type="submit" value="Subscribed" disabled />
                        </form>
                    }
                    else
                    {
                        <br />
                        <br />
                        <form class="ml-2" asp-controller="TrainingProgram"
                              asp-action="Subscribe" asp-route-id="@Model.Id" method="post">
                            <input class="btn-subscribe" type="submit" value="Subscribe" />
                        </form>
                    }
                    
                }
            }              
        </div>
    </div>
</div>